### ISSUE TITLE
operation not permitted running in docker on raspberry pi.

### ISSUE THREAD

**Issue by sgmoore** [MiguelNdeCarvalho/speedtest-exporter#167]
I'm posting this just in case anyone else has a similar issue.

I have been running this for a while, but after doing a docker-compose pull, the container was not starting and the logs had the **operation not permitted**  message coming from logging __init__

I was able to get around this by adding ` privileged : true` to the speedtest service section of the docker-compose.yml 

Not sure what the exact permissions required are.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

@sgmoore sorry for the late response, can you give me your `docker-compose.yml` content please? It should work without the privileged option enabled.

Thanks,
MiguelNdeCarvalho

**Comment by sgmoore** [comment]
[docker-compose.zip](https://github.com/MiguelNdeCarvalho/speedtest-exporter/files/9546058/docker-compose.zip)

Attached is my current docker-compose.yml file

The speedtest service block is

```

  speedtest:
    tty: true
    stdin_open: true
    expose:
      - 9798
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always
    networks:
      - back-tier
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged : true
    dns:
      - 1.1.1.1
      - 8.8.8.8

```

The `cap_add` section was added to try to fix the problem (but didn't), and then `privileged : true` was added and did fix the problem. The dns entries were added later.
