### ISSUE TITLE
Over 11,000 data points collected; Too many for Grafana

### ISSUE THREAD

**Issue by utdrmac** [MiguelNdeCarvalho/speedtest-exporter#170]
prometheus.yml:
```
  # speedtest
  - job_name: 'speedtest'
    scrape_interval: 10m
    scrape_timeout: 1m
    static_configs:
    - targets: ['metrics_speedtest:9798']
```

When trying to add metric to grafana:
> bad_data: exceeded maximum resolution of 11,000 points per timeseries.
<img width="975" alt="Screen Shot 2022-09-14 at 3 07 11 PM" src="https://user-images.githubusercontent.com/4413670/190252000-a9087a07-8e82-4187-90d8-5c23902a0052.png">

How is this creating 11,000 data points in 48hrs if I'm only grabbing the data every 10m?
