### ISSUE TITLE
change back to env cause issues

### ISSUE THREAD

**Issue by lundsec** [MiguelNdeCarvalho/speedtest-exporter#47]
Hey after you changed back to env instead of args its not possible to pass ENV interval to the speedtest

**Comment by MiguelNdeCarvalho** [comment]
Hey,

First of all are you running it inside of **Docker**? If so, let me know how you deployed it please (**docker cli** or **docker-composer**)

Thanks,
MiguelNdeCarvalho

**Comment by therock** [comment]
with docker-compose, so before you changed back to env i had in my compose file overwritten the command such that i could use ARGS.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Yap, I have removed the ARGS. I will try to do the **Documentation** today. Can you send me the docker-compose content please?

Thanks,
MiguelNdeCarvalho

**Comment by lundsec** [comment]
this is with command args, that currently dont do anything & env
```

version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}


services:
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter:latest
    ports:
      - "9798:9798"
    environment:
      - SPEEDTEST_SERVER=15658
    command:
      - python
      - -u
      - exporter.py
      - --interval=300
      - --server-id=15658
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=60d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    restart: always
```

**Comment by MiguelNdeCarvalho** [comment]
Hey,

I have release the docs yesterday. You find them [here](https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/).

Your `docker-compose.yml` should look like this:

``` yaml
version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}


services:
  speedtest-exporter:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    ports:
      - "9798:9798"
    environment:
      - SPEEDTEST_SERVER=15658
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=60d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    restart: always
```

As you can see we now don't set the `interval` between the tests on the exporter, we set it on the **Prometheus** side.

Your `prometheus.yml` should include this:

``` yaml
- job_name: 'speedtest-exporter'
  scrape_interval: 1h
  scrape_timeout: 1m
  static_configs:
    - targets: ['speedtest-exporter:9798']
```

In this example it will runs tests every 1 hour. If you need more help feel free to say.

Thanks,
MiguelNdeCarvalho
