### ISSUE TITLE
Unable to force speedtest server

### ISSUE THREAD

**Issue by Slonlo** [MiguelNdeCarvalho/speedtest-exporter#88]
This is my first issue on GitHub, so if I'm missing anything context or formatting wise, please correct me. I'm trying to force a specific speedtest server because there is one near me (32032) that is always slow. I tried using the 

```
environment:
SPEEDTEST_SERVER=19299
```

in docker-compose.yml to force it to use the server I want. 

```
speedtest:
    tty: true                                                                          
    stdin_open: true
    environment:
     - SPEEDTEST_SERVER=19229
    expose:
     - 9798
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    restart: always
    networks:
      - back-tier
```

It doesn't seem to be working because it's still using whatever server it wants according to the metrics.

```
# TYPE speedtest_server_id gauge
speedtest_server_id  #14231.0
```
